python: can't open file '/tmp/gptme-evals-c0a3v74r/hello.py': [Errno 2] No such file or directory
