python: can't open file '/tmp/gptme-evals-h7q76dhh/prime.py': [Errno 2] No such file or directory
