python: can't open file '/tmp/gptme-evals-0h32d0zw/hello.py': [Errno 2] No such file or directory
