python: can't open file '/tmp/gptme-evals-q80ps9m1/prime.py': [Errno 2] No such file or directory
