python: can't open file '/tmp/gptme-evals-m1jgpmog/prime.py': [Errno 2] No such file or directory
