python: can't open file '/tmp/gptme-evals-maxe6345/hello.py': [Errno 2] No such file or directory
