python: can't open file '/tmp/gptme-evals-hx38a0qf/hello.py': [Errno 2] No such file or directory
