python: can't open file '/tmp/gptme-evals-611vkdry/prime.py': [Errno 2] No such file or directory
