python: can't open file '/tmp/gptme-evals-co2p4d74/hello.py': [Errno 2] No such file or directory
