python: can't open file '/tmp/gptme-evals-1dbpreow/prime.py': [Errno 2] No such file or directory
