python: can't open file '/tmp/gptme-evals-08_l6v1y/hello.py': [Errno 2] No such file or directory
