python: can't open file '/tmp/gptme-evals-e81ia86q/prime.py': [Errno 2] No such file or directory
