python: can't open file '/tmp/gptme-evals-b_96_q53/prime.py': [Errno 2] No such file or directory
