python: can't open file '/tmp/gptme-evals-dmyl83kc/hello.py': [Errno 2] No such file or directory
