python: can't open file '/tmp/gptme-evals-w4e_sbd5/hello.py': [Errno 2] No such file or directory
