python: can't open file '/tmp/gptme-evals-a9bxu2lg/hello.py': [Errno 2] No such file or directory
