python: can't open file '/tmp/gptme-evals-tyibbx7i/prime.py': [Errno 2] No such file or directory
