python: can't open file '/tmp/gptme-evals-_o0icrs_/prime.py': [Errno 2] No such file or directory
