python: can't open file '/tmp/gptme-evals-wjygcxo0/hello.py': [Errno 2] No such file or directory
