python: can't open file '/tmp/gptme-evals-w35nrwv5/hello.py': [Errno 2] No such file or directory
