python: can't open file '/tmp/gptme-evals-0dhnydxc/prime.py': [Errno 2] No such file or directory
