python: can't open file '/tmp/gptme-evals-bt6mwb2f/hello.py': [Errno 2] No such file or directory
