python: can't open file '/tmp/gptme-evals-2tsfdw62/prime.py': [Errno 2] No such file or directory
