python: can't open file '/tmp/gptme-evals-xe9hge63/prime.py': [Errno 2] No such file or directory
