python: can't open file '/tmp/gptme-evals-ldolw7f2/hello.py': [Errno 2] No such file or directory
