python: can't open file '/tmp/gptme-evals-bpa27nt9/prime.py': [Errno 2] No such file or directory
