python: can't open file '/tmp/gptme-evals-m8f1sj38/prime.py': [Errno 2] No such file or directory
