python: can't open file '/tmp/gptme-evals-ln1mx2nl/hello.py': [Errno 2] No such file or directory
