python: can't open file '/tmp/gptme-evals-16q7dhth/hello.py': [Errno 2] No such file or directory
