python: can't open file '/tmp/gptme-evals-v2jktwy0/hello.py': [Errno 2] No such file or directory
