python: can't open file '/tmp/gptme-evals-c93a1kk0/hello.py': [Errno 2] No such file or directory
