python: can't open file '/tmp/gptme-evals-d3k1io2x/hello.py': [Errno 2] No such file or directory
